// <auto-generated />
using System;
using IceCity.EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IceCity.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729150327_AddRowVersion")]
    partial class AddRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IceCity.EFCore.Entities.DailyUsage", b =>
                {
                    b.Property<int>("DailyUsageId")
                        .HasColumnType("int");

                    b.Property<int>("HeaterId")
                        .HasColumnType("int");

                    b.Property<decimal>("HeaterValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DailyUsageId");

                    b.HasIndex("HeaterId");

                    b.HasIndex("HouseId");

                    b.ToTable("DailyUsages", (string)null);
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.Heater", b =>
                {
                    b.Property<int>("HeaterId")
                        .HasColumnType("int");

                    b.Property<string>("HeaterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("PowerValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("HeaterId");

                    b.HasIndex("HouseId");

                    b.ToTable("Heaters", (string)null);
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.House", b =>
                {
                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("CityZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("HouseId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Houses", (string)null);
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.MonthlyReport", b =>
                {
                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("MedianHeaterValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MonthlyAverageCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("ReportMonth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalWorkingHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ReportId");

                    b.HasIndex("HouseId");

                    b.ToTable("MonthlyReports", (string)null);
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Owners", (string)null);
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.DailyUsage", b =>
                {
                    b.HasOne("IceCity.EFCore.Entities.Heater", "Heater")
                        .WithMany("DailyUsages")
                        .HasForeignKey("HeaterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IceCity.EFCore.Entities.House", "House")
                        .WithMany("dailyUsages")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heater");

                    b.Navigation("House");
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.Heater", b =>
                {
                    b.HasOne("IceCity.EFCore.Entities.House", "House")
                        .WithMany("heaters")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.House", b =>
                {
                    b.HasOne("IceCity.EFCore.Entities.Owner", "owner")
                        .WithMany("Houses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.MonthlyReport", b =>
                {
                    b.HasOne("IceCity.EFCore.Entities.House", "House")
                        .WithMany("monthlyReports")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.Heater", b =>
                {
                    b.Navigation("DailyUsages");
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.House", b =>
                {
                    b.Navigation("dailyUsages");

                    b.Navigation("heaters");

                    b.Navigation("monthlyReports");
                });

            modelBuilder.Entity("IceCity.EFCore.Entities.Owner", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
